# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  - push

env:
  JWT_PASSPHRASE: 4CNbgin1cB0IaTFE!txhBGpJmv^pAPuw$%Fkice^GR!K1q%eP@pj$OSladA5gcyy
  MONGODB_DBNAME: stream_particles_test
  URL_FRONT: http://localhost:4000
  URL_API: http://localhost:4000/api
  URL_UPLOAD_PATH: http://localhost:4000/uploads

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0

      - name: Install
        run: npm ci

      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1

      - name: Test
        run: npm run test

      - name: Linter
        run: npm run lint
